### ISSUE TITLE
thor: Panic while executing python scripts

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/managarm#193]
While running `python3 get-pip.py` I managed to get thor to panic consistently with the following error

```
Panic!
Fault #14, from unexpected cs: 0x60, ip: 0xffffffff80078772
Error code: 0x3, SS: 0x38, RSP: 0xffffe000009bbe48
```

`addr2line` gives the following
```
dennis@DENNIS-MAIN-LAPTOP-SIDUCTION:~/managarm-clone/build$ addr2line -e packages/managarm-kernel/usr/managarm/bin/thor 
0xffffffff80078772
/home/dennis/managarm-clone/build/pkg-builds/managarm-kernel/../../../src/managarm/frigg/include/frigg/arch_x86/atomic_impl.hpp:102
```

A (not so useful) gdb backtrace is provided for completeness
```
(gdb) bt
#0  friggPanic () at ../../../src/managarm/kernel/thor/generic/core.cpp:274
#1  0xffffffff80008f7c in onPlatformFault (image=..., number=<optimized out>) at ../../../src/managarm/frigg/include/frigg/debug.hpp:265
#2  0xffffffff80000518 in faultStubPage () at ../../../src/managarm/kernel/thor/arch/x86/stubs.S:124
#3  0xffffffff800210a0 in ?? () at ../../../src/managarm/subprojects/frigg/include/frg/rbtree.hpp:444
#4  0xffffffff800210a0 in ?? () at ../../../src/managarm/subprojects/frigg/include/frg/rbtree.hpp:444
#5  0x0000000000001f78 in ?? ()
#6  0x0000000000000078 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)
```

**Comment by avdgrinten** [comment]
I think this bug has been found and fixed by KASAN. Can you confirm?

**Comment by Dennisbonke** [comment]
A quick hello world test script runs successfully. I'd say this issue has been fixed.
