### ISSUE TITLE
async::shared_mutex assertion failure in page fault handling

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/managarm#372]
When running `git pull` on an imported git repository, there is about 50% chance that the following assertion is triggered
```
Assertion failed: st_ == state::shared
In function unlock_shared at ../../../src/managarm/subprojects/libasync/include/async/mu
```

The following stacktrace is produced
```
(gdb) bt
#0  thor::panic () at ../../../src/managarm/kernel/thor/generic/debug.cpp:149
#1  thor::PanicSink::operator() (this=<optimized out>, msg=<optimized out>) at ../../../src/managarm/kernel/thor/generic/debug.cpp:187
#2  0xffffffff800178b1 in frg::stack_buffer_logger<thor::PanicSink, 128ul>::_emit (this=<optimized out>, 
    message=0xffffe0000016fc88 "Assertion failed: st_ == state::shared\nIn function unlock_shared at ../../../src/managarm/subprojects/libasync/include/async/mu")
    at ../../../src/managarm/subprojects/frigg/include/frg/logging.hpp:80
#3  frg::stack_buffer_logger<thor::PanicSink, 128ul>::item::append (this=0xffffe0000016fc80, str=<optimized out>) at ../../../src/managarm/subprojects/frigg/include/frg/logging.hpp:56
#4  frg::format_object<frg::stack_buffer_logger<thor::PanicSink, 128ul>::item> (object=<optimized out>, formatter=...) at ../../../src/managarm/subprojects/frigg/include/frg/formatting.hpp:376
#5  frg::format<char const*, frg::stack_buffer_logger<thor::PanicSink, 128ul>::item> (formatter=..., object=<optimized out>) at ../../../src/managarm/subprojects/frigg/include/frg/formatting.hpp:487
#6  frg::stack_buffer_logger<thor::PanicSink, 128ul>::item::operator<< <char const*> (this=0xffffe0000016fc80, object=<optimized out>) at ../../../src/managarm/subprojects/frigg/include/frg/logging.hpp:30
#7  0xffffffff80017406 in __assert_fail (assertion=<optimized out>, file=0xa <error: Cannot access memory at address 0xa>, line=328, function=<optimized out>)
    at ../../../src/managarm/kernel/thor/generic/debug.cpp:196
#8  0xffffffff800126ab in async::detail::shared_mutex::unlock_shared (this=0xffffe0000a1b3060) at ../../../src/managarm/subprojects/libasync/include/async/mutex.hpp:328
#9  0xffffffff80009413 in frg::shared_lock<async::detail::shared_mutex>::unlock (this=<optimized out>) at ../../../src/managarm/subprojects/frigg/include/frg/mutex.hpp:128
#10 frg::shared_lock<async::detail::shared_mutex>::~shared_lock (this=<optimized out>) at ../../../src/managarm/subprojects/frigg/include/frg/mutex.hpp:112
#11 thor::VirtualSpace::handleFault (this=<optimized out>, address=<optimized out>, faultFlags=<optimized out>, wq=...) at ../../../src/managarm/kernel/thor/generic/address-space.cpp:832
#12 0xffffffff8000528a in thor::Mapping::runEvictionLoop (this=<optimized out>) at ../../../src/managarm/kernel/thor/generic/address-space.cpp:236
#13 0xffffffff80131f86 in thor::PageBinding::shootdown (this=0xffffffff801a3098 <thor::staticBootCpuContext+12664>) at ../../../src/managarm/kernel/thor/arch/x86/paging.cpp:317
#14 0xffffffff8012a91f in onPlatformShootdown (image=...) at ../../../src/managarm/kernel/thor/arch/x86/ints.cpp:459
#15 0xffffffff80001ec7 in thorRtIpiShootdown () at ../../../src/managarm/kernel/thor/arch/x86/stubs.S:445
#16 0x0000000000000001 in ?? ()
#17 0xffffffff80184be0 in thor::kernelHeap ()
#18 0xffffe000004c0000 in ?? ()
#19 0xffffe000004bfd20 in ?? ()
#20 0xffffffff80184be0 in thor::kernelHeap ()
#21 0xffffe00000480000 in ?? ()
#22 0x0000000000000000 in ?? ()
(gdb) 
```
<br>
To reproduce, one needs to build `git`, as shown in managarm/bootstrap-managarm#128, copy an git repository to the filesystem (git clone is not working, so this needs to be done from the host), I used managarm as a testbed, boot Managarm, cd into the directory and execute `git pull`. Depending on a bit of luck 3 things have been observed to happen, either git dies due to curl not fully working (most common), the issue above happens (less common), or an unhandled page fault occurs (only once observed, not sure if it's reproducible).

**Comment by avdgrinten** [comment]
This is fixed by a recent libasync commit.
