### ISSUE TITLE
thor: Assertion failure during execution of the MiniBrowser

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/managarm#395]
While testing the `MiniBrowser` from `WebKitGTK2`, the following assertion is sometimes hit
```
posix: fork supercall
Assertion failed: osIt->state == CowState::hasCopy
In function fork at ../../../src/managarm/kernel/thor/generic/memory-view.cp
```

The following stacktrace has been pulled from gdb
```
(gdb) bt
#0  thor::panic () at ../../../src/managarm/kernel/thor/generic/debug.cpp:149
#1  thor::PanicSink::operator() (this=<optimized out>, msg=<optimized out>) at ../../../src/managarm/kernel/thor/generic/debug.cpp:187
#2  0xffffffff80018661 in frg::stack_buffer_logger<thor::PanicSink, 128ul>::_emit (this=<optimized out>, 
    message=0xffffe00000c7fca8 "Assertion failed: osIt->state == CowState::hasCopy\nIn function fork at ../../../src/managarm/kernel/thor/generic/memory-view.cp")
    at ../../../src/managarm/subprojects/frigg/include/frg/logging.hpp:80
#3  frg::stack_buffer_logger<thor::PanicSink, 128ul>::item::append (this=0xffffe00000c7fca0, str=<optimized out>) at ../../../src/managarm/subprojects/frigg/include/frg/logging.hpp:56
#4  frg::format_object<frg::stack_buffer_logger<thor::PanicSink, 128ul>::item> (object=<optimized out>, formatter=...) at ../../../src/managarm/subprojects/frigg/include/frg/formatting.hpp:375
#5  frg::format<char const*, frg::stack_buffer_logger<thor::PanicSink, 128ul>::item> (formatter=..., object=<optimized out>) at ../../../src/managarm/subprojects/frigg/include/frg/formatting.hpp:486
#6  frg::stack_buffer_logger<thor::PanicSink, 128ul>::item::operator<< <char const*> (this=0xffffe00000c7fca0, object=<optimized out>) at ../../../src/managarm/subprojects/frigg/include/frg/logging.hpp:30
#7  0xffffffff800181b6 in __assert_fail (assertion=<optimized out>, file=0xa <error: Cannot access memory at address 0xa>, line=1502, function=<optimized out>)
    at ../../../src/managarm/kernel/thor/generic/debug.cpp:196
#8  0xffffffff800828ce in thor::CopyOnWriteMemory::fork (this=<optimized out>, receiver=...) at ../../../src/managarm/kernel/thor/generic/memory-view.cpp:1502
#9  0xffffffff800448a1 in thor::MemoryView::ForkOperation<thor::Thread::asyncBlockCurrent<thor::MemoryView::ForkSender>(thor::MemoryView::ForkSender, thor::WorkQueue*)::Receiver>::start() (this=<optimized out>)
    at ../../../src/managarm/kernel/thor/generic/thor-internal/memory-view.hpp:535
#10 async::cpo_types::start_inline_cpo::operator()<thor::MemoryView::ForkOperation<thor::Thread::asyncBlockCurrent<thor::MemoryView::ForkSender>(thor::MemoryView::ForkSender, thor::WorkQueue*)::Receiver>&>(thor::MemoryView::ForkOperation<thor::Thread::asyncBlockCurrent<thor::MemoryView::ForkSender>(thor::MemoryView::ForkSender, thor::WorkQueue*)::Receiver>&) const (this=<optimized out>, op=...)
    at ../../../src/managarm/subprojects/libasync/include/async/execution.hpp:70
#11 thor::Thread::asyncBlockCurrent<thor::MemoryView::ForkSender> (s=..., wq=0xffffe00000e340e8) at ../../../src/managarm/kernel/thor/generic/thor-internal/thread.hpp:153
#12 0xffffffff80025e1b in thor::Thread::asyncBlockCurrent<thor::MemoryView::ForkSender> (s=...) at ../../../src/managarm/kernel/thor/generic/thor-internal/thread.hpp:75
#13 helForkMemory (handle=<optimized out>, forkedHandle=0xffffe00000c7ff48) at ../../../src/managarm/kernel/thor/generic/hel.cpp:617
#14 0xffffffff80078461 in thor::handleSyscall (image=...) at ../../../src/managarm/kernel/thor/generic/main.cpp:602
#15 0xffffffff801316bb in onPlatformSyscall (image=...) at ../../../src/managarm/kernel/thor/arch/x86/ints.cpp:439
#16 0xffffffff80001fc1 in syscallStub () at ../../../src/managarm/kernel/thor/arch/x86/stubs.S:487
#17 0x0000000000000028 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) 
```

I must note that I'm running with `-smp 1`, so no multicore.

**Comment by Dennisbonke** [comment]
This seems to have been fixed at this point in time.
