### ISSUE TITLE
Kernel panic while running abiword

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/managarm#443]
While running `abiword`, the following kernel panic is observed quite early in program startup.
```
Assertion failed: (offset + length) / kPageSize <= _managed->numPages
In function updateRange at ../../../src/managarm/kernel/t
```
as this tells us not that much, I've pulled a backtrace, found [here](https://mlibc.is-fi.re/9gxWspS.log) and the relevant parts can be found below
```
#7  __assert_fail (assertion=0xffffffff8014aae2 "(offset + length) / kPageSize <= _managed->numPages", file=0xffffffff8014a66f "../../../src/managarm/kernel/thor/generic/memory-view.cpp", line=1065, 
    function=0xffffffff8014aad6 "updateRange") at ../../../src/managarm/kernel/thor/generic/debug.cpp:199
#8  0xffffffff8007b90d in thor::BackingMemory::updateRange (this=0xffffe000070271b0, type=thor::ManageRequest::writeback, offset=0, length=4096) at ../../../src/managarm/kernel/thor/generic/memory-view.cpp:1065
#9  0xffffffff8002dfa7 in helUpdateMemory (handle=<optimized out>, type=2, offset=233, length=0) at ../../../src/managarm/kernel/thor/generic/hel.cpp:1393
#10 0xffffffff80073698 in thor::handleSyscall (image=image@entry=...) at ../../../src/managarm/kernel/thor/generic/main.cpp:653
#11 0xffffffff80109e4b in onPlatformSyscall (image=...) at ../../../src/managarm/kernel/thor/arch/x86/ints.cpp:439
#12 0xffffffff80001fc1 in syscallStub () at ../../../src/managarm/kernel/thor/arch/x86/stubs.S:487
#13 0x000000000000002f in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)
```

**Comment by qookei** [comment]
I feel like the root cause of this is actually related to #175
