### ISSUE TITLE
thor: kernel panic when running terminal application on master

### ISSUE THREAD

**Issue by ElectrodeYT** [managarm/managarm#452]
Backtrace:
```pwndbg> bt
#0  thor::panic () at ../../../src/managarm/kernel/thor/generic/debug.cpp:149
#1  thor::PanicSink::operator() (this=<optimized out>, msg=<optimized out>) at ../../../src/managarm/kernel/thor/generic/debug.cpp:190
#2  0xffffffff801081a5 in frg::stack_buffer_logger<thor::PanicSink, 128ul>::_emit (this=0xffffffff8015d978 <thor::pioLogHandler>, message=0xffffe00000e6fb40 "Fault #14, with IF=0, cs: 0x30, ip: 0xffffffff80014855\nError code: 0x0, SS: 0x38, RSP: 0xffffe00000e6fcd8") at ../../../src/managarm/subprojects/frigg/include/frg/logging.hpp:92
#3  frg::stack_buffer_logger<thor::PanicSink, 128ul>::item::operator<< (this=0xffffe00000e6fb38) at ../../../src/managarm/subprojects/frigg/include/frg/logging.hpp:44
#4  onPlatformFault (image=..., number=14) at ../../../src/managarm/kernel/thor/arch/x86/ints.cpp:333
#5  0xffffffff80000518 in faultStubPage () at ../../../src/managarm/kernel/thor/arch/x86/stubs.S:200
#6  0xffffffff80014855 in frg::_list::intrusive_list<async::detail::shared_mutex::node, frg::locate_member<async::detail::shared_mutex::node, frg::_list::intrusive_list_hook<async::detail::shared_mutex::node*, async::detail::shared_mutex::node*>, &async::detail::shared_mutex::node::hook> >::front (this=0xffffe000068a3e70) at ../../../src/managarm/subprojects/frigg/include/frg/list.hpp:148
#7  async::detail::shared_mutex::unlock (this=0xffffe000068a3e60) at ../../../src/managarm/subprojects/libasync/include/async/mutex.hpp:313
#8  0xffffffff800094a8 in frg::unique_lock<async::detail::shared_mutex>::unlock (this=<optimized out>) at ../../../src/managarm/subprojects/frigg/include/frg/mutex.hpp:63
#9  frg::unique_lock<async::detail::shared_mutex>::~unique_lock (this=<optimized out>) at ../../../src/managarm/subprojects/frigg/include/frg/mutex.hpp:47
#10 thor::VirtualSpace::map (this=<optimized out>, slice=..., address=<optimized out>, offset=<optimized out>, length=<optimized out>, flags=<optimized out>) at ../../../src/managarm/kernel/thor/generic/address-space.cpp:508
#11 0xffffffff80046977 in std::experimental::coroutine_handle<void>::resume (this=<optimized out>) at ../../../src/managarm/subprojects/cxxshim/clang-coroutine/include/experimental/coroutine:40
#12 coroutine_operation<frg::expected<thor::Error, unsigned long>, thor::Thread::asyncBlockCurrent<coroutine<frg::expected<thor::Error, unsigned long> > >(coroutine<frg::expected<thor::Error, unsigned long> >, thor::WorkQueue*)::Receiver>::start_inline() (this=0xffffe00000e6fdb8) at ../../../src/managarm/kernel/thor/generic/thor-internal/coroutine.hpp:293
#13 async::cpo_types::start_inline_cpo::operator()<coroutine_operation<frg::expected<thor::Error, unsigned long>, thor::Thread::asyncBlockCurrent<coroutine<frg::expected<thor::Error, unsigned long> > >(coroutine<frg::expected<thor::Error, unsigned long> >, thor::WorkQueue*)::Receiver>&>(coroutine_operation<frg::expected<thor::Error, unsigned long>, thor::Thread::asyncBlockCurrent<coroutine<frg::expected<thor::Error, unsigned long> > >(coroutine<frg::expected<thor::Error, unsigned long> >, thor::WorkQueue*)::Receiver>&) const (op=..., this=<optimized out>) at ../../../src/managarm/subprojects/libasync/include/async/execution.hpp:68
#14 thor::Thread::asyncBlockCurrent<coroutine<frg::expected<thor::Error, unsigned long> > > (s=..., wq=0xffffe00000a240e8) at ../../../src/managarm/kernel/thor/generic/thor-internal/thread.hpp:153
#15 0xffffffff800295ff in thor::Thread::asyncBlockCurrent<coroutine<frg::expected<thor::Error, unsigned long> > > (s=...) at ../../../src/managarm/kernel/thor/generic/thor-internal/thread.hpp:75
#16 helMapMemory (memory_handle=<optimized out>, space_handle=<optimized out>, pointer=0x0, offset=0, length=16777216, flags=<optimized out>, actualPointer=0xffffe00000e6ff48) at ../../../src/managarm/kernel/thor/generic/hel.cpp:813
#17 0xffffffff80073a46 in thor::handleSyscall (image=image@entry=...) at ../../../src/managarm/kernel/thor/generic/main.cpp:666
#18 0xffffffff80109feb in onPlatformSyscall (image=...) at ../../../src/managarm/kernel/thor/arch/x86/ints.cpp:439
#19 0xffffffff80001fc1 in syscallStub () at ../../../src/managarm/kernel/thor/arch/x86/stubs.S:487
#20 0x000000000000002c in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
Exception occurred: Error: monitor info mem output didn't pass a sanity check (<class 'AssertionError'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
Python Exception <class 'AssertionError'>: monitor info mem output didn't pass a sanity check
pwndbg> 
```

Fault error on console:
```
Fault #14, with IF=0, cs: 0x30, ip: 0xffffffff80014855
Error code: 0x0, SS: 0x38, RSP: 0xffffe00000e6fcd8
```

**Comment by 64** [comment]
is this reproducible? there's a good chance it's fixed by https://github.com/managarm/libasync/pull/15

**Comment by Dennisbonke** [comment]
We're testing a previous managarm commit to verify something else, hold that for a second.

**Comment by ElectrodeYT** [comment]
Fixed
