### ISSUE TITLE
Different kernel assertion related to memory while running chromium

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/managarm#530]
While running chromium (as `chromium --single-process` in a somewhat successful attempt to work around #529) (with -smp 1), I consistently run into the following assert.
```
Assertion failed: status & page_status::present
In function remapPresentPagesByCursor at ../../../src/managarm/kernel/thor/generic/thor-internal/address-space.hpp:50
```
I have the following backtrace for this
```
(gdb) bt
#0  thor::panic () at ../../../src/managarm/kernel/thor/generic/debug.cpp:143
#1  thor::PanicSink::operator() (this=<optimized out>, msg=<optimized out>) at ../../../src/managarm/kernel/thor/generic/debug.cpp:184
#2  frg::stack_buffer_logger<thor::PanicSink, 256ul>::_emit (this=<optimized out>, message=<optimized out>) at /var/lib/managarm-buildenv/build/system-root/usr/share/frigg/include/frg/logging.hpp:98
#3  frg::stack_buffer_logger<thor::PanicSink, 256ul>::item::operator<< (this=0xffffe00004c2f620) at /var/lib/managarm-buildenv/build/system-root/usr/share/frigg/include/frg/logging.hpp:50
#4  __assert_fail (assertion=0xffffffff8013f5c0 "status & page_status::present", file=<optimized out>, line=<optimized out>, function=<optimized out>) at ../../../src/managarm/kernel/thor/generic/debug.cpp:193
#5  0xffffffff8000f1ce in thor::remapPresentPagesByCursor<thor::ClientPageSpace::Cursor, thor::ClientPageSpace> (ps=<optimized out>, va=140694540783616, view=0xffffe0000903f830, offset=147652608, 
    size=<optimized out>, flags=5) at ../../../src/managarm/kernel/thor/generic/thor-internal/address-space.hpp:50
#6  0xffffffff800082b3 in thor::VirtualSpace::protect (this=<optimized out>, address=<optimized out>, length=<optimized out>, flags=<optimized out>)
    at ../../../src/managarm/kernel/thor/generic/address-space.cpp:559
#7  0xffffffff80012d26 in async::detail::shared_mutex::unlock_shared (this=<optimized out>) at ../../../src/managarm/subprojects/libasync/include/async/mutex.hpp:354
#8  0xffffffff8000962d in frg::shared_lock<async::detail::shared_mutex>::unlock (this=<optimized out>) at /var/lib/managarm-buildenv/build/system-root/usr/share/frigg/include/frg/mutex.hpp:128
#9  frg::shared_lock<async::detail::shared_mutex>::~shared_lock (this=<optimized out>) at /var/lib/managarm-buildenv/build/system-root/usr/share/frigg/include/frg/mutex.hpp:112
#10 thor::VirtualSpace::handleFault (this=<optimized out>, address=<optimized out>, faultFlags=<optimized out>, wq=...) at ../../../src/managarm/kernel/thor/generic/address-space.cpp:676
#11 0xffffffff80005570 in thor::Mapping::runEvictionLoop (this=<optimized out>) at ../../../src/managarm/kernel/thor/generic/address-space.cpp:313
#12 0xffffffff800850f6 in async::post_ack_mechanism<thor::RangeToEvict>::post_operation<async::sender_awaiter<async::post_ack_mechanism<thor::RangeToEvict>::post_sender, void>::receiver>::start_inline()::{lambda()#1}::operator()() const (this=this@entry=0xffffe00004c2fa58) at ../../../src/managarm/subprojects/libasync/include/async/post-ack.hpp:99
#13 0xffffffff8007fe93 in async::post_ack_mechanism<thor::RangeToEvict>::post_operation<async::sender_awaiter<async::post_ack_mechanism<thor::RangeToEvict>::post_sender, void>::receiver>::start_inline (
    this=0xffffe00008e06400) at ../../../src/managarm/subprojects/libasync/include/async/post-ack.hpp:66
#14 async::cpo_types::start_inline_cpo::operator()<async::post_ack_mechanism<thor::RangeToEvict>::post_operation<async::sender_awaiter<async::post_ack_mechanism<thor::RangeToEvict>::post_sender, void>::receiver>&> (op=..., this=<optimized out>) at ../../../src/managarm/subprojects/libasync/include/async/execution.hpp:68
#15 async::sender_awaiter<async::post_ack_mechanism<thor::RangeToEvict>::post_sender, void>::await_suspend (this=0xffffe00008e06400, h=...)
    at ../../../src/managarm/subprojects/libasync/include/async/basic.hpp:121
#16 thor::CopyOnWriteMemory::fetchRange (this=<optimized out>, offset=<optimized out>, wq=...) at ../../../src/managarm/kernel/thor/generic/memory-view.cpp:1778
#17 0xffffffff8007b4f6 in coroutine<frg::expected<thor::Error, void> >::promise_type::final_suspend()::awaiter::await_suspend(std::coroutine_handle<void>) (this=<optimized out>)
    at ../../../src/managarm/kernel/thor/generic/thor-internal/coroutine.hpp:117
#18 thor::MemoryView::copyFrom (this=<optimized out>, offset=<optimized out>, pointer=<optimized out>, size=<optimized out>, wq=...) at ../../../src/managarm/kernel/thor/generic/memory-view.cpp:269
#19 0xffffffff800cd867 in thor::WorkQueue::run (this=0xffffe00004e1c140) at ../../../src/managarm/kernel/thor/generic/work-queue.cpp:108
#20 0xffffffff80040a55 in thor::Thread::asyncBlockCurrent<coroutine<frg::expected<thor::Error, void> > > (s=..., wq=0xffffe00004e1c140) at ../../../src/managarm/kernel/thor/generic/thor-internal/thread.hpp:160
#21 0xffffffff8006aa2a in thor::handlePageFault (image=..., address=<optimized out>, address@entry=94645478, errorCode=<optimized out>) at ../../../src/managarm/kernel/thor/generic/main.cpp:447
#22 0xffffffff80101768 in onPlatformFault (image=..., number=14) at ../../../src/managarm/kernel/thor/arch/x86/ints.cpp:351
#23 0xffffffff80000518 in faultStubPage () at ../../../src/managarm/kernel/thor/arch/x86/stubs.S:200
#24 0x0000000005a42ce6 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)
```
As this is reproducible, I'm available to provide further information or a testing image if requested.

**Comment by no92** [comment]
Fixed by #532.
