### ISSUE TITLE
gfx/bochs: garbled output

### ISSUE THREAD

**Issue by no92** [managarm/managarm#565]
Booting with the bochs driver into kmscon leads to garbled screen output. To reproduce, it is sufficient to run `../src/scripts/vm-util.py qemu --gfx bga` and select the non-plainfb kmscon boot option.

**Comment by qookei** [comment]
The driver seems to crash, either failing with
```
HEL_CHECK failed: helAlterMemoryIndirection(_memory.getHandle(), bo->getMapping() >> 32, boMemory.getHandle(), boOffset, bo->getSize())
    In file ../../../src/managarm/core/drm/src/core.cpp on line 72

Illegal descriptor for this operation


thor: Panic in server /usr/bin/gfx_bochs
```
when running kmscon, or crashing with a #GP when running weston
```
thor: Unhandled general fault, faulting ip: 0x41064844
thor: general fault in server.
Last ip: 0x41064844
thor: Panic in server /usr/bin/gfx_bochs
```

**Comment by qookei** [comment]
This hasn't been fixed yet, but in the meanwhile the behavior when launching Weston has changed. Now, instead of a crash in the driver, Weston reports that it fails to find the primary plane:
```
[11:31:37.766] DRM: head 'Virtual-0' found, connector 3 is connected, EDID make 'unknown', model 'unknown', serial 'unknown'
               Supported EOTF modes: SDR
[11:31:37.779] Registered plugin API 'weston_drm_output_api_v1' of size 40
[11:31:37.782] Color manager: no-op
[11:31:37.786] Output 'Virtual-0' attempts EOTF mode: SDR
[11:31:37.788] Output 'Virtual-0' using color profile: built-in default sRGB SDR profile
[11:31:37.790] Failed to find primary plane for output Virtual-0
[11:31:37.791] Enabling output "Virtual-0" failed.
[11:31:37.795] Error: cannot enable output 'Virtual-0' without heads.
```

After which it tries to shut down, and crashes in some udev code related to removing input devices (but that's unrelated to this issue):
```
#0  weston_launcher_close (launcher=0x0, fd=21) at ../../../src/ports/weston/libweston/launcher-util.c:84
#1  0x0000000042416ae5 in evdev_device_suspend (device=device@entry=0x7ffffec69800) at ../../../src/ports/libinput/src/evdev.c:2990
#2  0x0000000042416d7e in evdev_device_remove (device=0x7ffffec69800) at ../../../src/ports/libinput/src/evdev.c:3080
#3  0x00000000424357fd in udev_input_remove_devices (input=<optimized out>) at ../../../src/ports/libinput/src/udev-seat.c:252
#4  udev_input_disable (libinput=0x7ffffebf8800) at ../../../src/ports/libinput/src/udev-seat.c:271
#5  0x0000000042411d85 in libinput_unref (libinput=0x7ffffebf8800) at ../../../src/ports/libinput/src/libinput.c:1962
#6  0x0000000042c0d31c in drm_destroy (backend=0x7fffff73fc00) at ../../../src/ports/weston/libweston/backend-drm/drm.c:3171
#7  0x0000000041227e27 in weston_compositor_destroy (compositor=0x7ffffec7f800) at ../../../src/ports/weston/libweston/compositor.c:9007
#8  0x000000004100ca59 in wet_main (argc=<optimized out>, argv=<optimized out>, test_data=0x0) at ../../../src/ports/weston/compositor/main.c:4212
#9  0x000000004184131a in __mlibc_entry (entry_stack=<optimized out>, main_fn=0x400380 <main>) at ../../../src/mlibc/sysdeps/managarm/generic/entry.cpp:130
#10 0x0000000000400396 in _start ()
```
