### ISSUE TITLE
Kernel assert fail in writePartialSpace

### ISSUE THREAD

**Issue by Qwinci** [managarm/managarm#583]
```
Assertion failed: limitInMapping
In function writePartialSpace at ../../../src/managarm/kernel/thor/generic/address-space.cpp:1186
```
this happens when running Minecraft server.

Here is a part of the log, because there is a huge list of the same pagefault over and over after that https://gist.github.com/Qwinci/3e66b640744868628f9ec5f80b34adbb

gdb backtrace:
```
#0  thor::panic ()
    at ../../../src/managarm/kernel/thor/generic/debug.cpp:143
#1  thor::PanicSink::finalize (this=<optimized out>)
    at ../../../src/managarm/kernel/thor/generic/debug.cpp:186
#2  frg::stack_buffer_logger<thor::PanicSink, 256ul>::_finalize (this=<optimized out>, done=<optimized out>)
    at /var/lib/managarm-buildenv/build/system-root/usr/share/frigg/include/frg/logging.hpp:103
#3  frg::stack_buffer_logger<thor::PanicSink, 256ul>::item::~item (this=0xffffe00000effd40)
    at /var/lib/managarm-buildenv/build/system-root/usr/share/frigg/include/frg/logging.hpp:38
#4  __assert_fail (assertion=<optimized out>, 
    file=0xffffffff80125c68 "../../../src/managarm/kernel/thor/generic/address-space.cpp", line=1186, 
    function=0xffffffff80126331 "writePartialSpace")
    at ../../../src/managarm/kernel/thor/generic/debug.cpp:193
#5  0xffffffff8000bff0 in thor::VirtualSpace::writePartialSpace (this=<optimized out>, address=<optimized out>, 
    buffer=<optimized out>, size=<optimized out>, wq=...)
    at ../../../src/managarm/kernel/thor/generic/address-space.cpp:1186
#6  0xffffffff800c3bf7 in thor::WorkQueue::run (
    this=0xffffe00000a240f0)
    at ../../../src/managarm/kernel/thor/generic/work-queue.cpp:108
#7  0xffffffff80060e12 in thor::handleSyscall (
    image=image@entry=...)
    at ../../../src/managarm/kernel/thor/generic/main.cpp:889
#8  0xffffffff800f234b in onPlatformSyscall (image=...)
    at ../../../src/managarm/kernel/thor/arch/x86/ints.cpp:442
#9  0xffffffff80001fc1 in syscallStub ()
    at ../../../src/managarm/kernel/thor/arch/x86/stubs.S:487
#10 0x0000000000000000 in ?? ()
```

**Comment by avdgrinten** [comment]
This is probably fixed by @48cf's recent changes (?).
